- name: Install prerequisites
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
      - gpg

- name: Import GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository to sources
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  become: yes
  ansible.builtin.apt:
    name: grafana
    update_cache: yes

- name: Start and enable Grafana
  become: yes
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes
