- name: Install apache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apache2
      - libapache2-mod-php

- name: Start apache
  become: yes
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started
