---
- name: install lighttpd
  hosts: debian
  
  tasks:
    - name: install lighttpd
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        name:
          - lighttpd

    - name: start lighttpd
      become: yes
      ansible.builtin.service:
        name: lighttpd
        enabled: true
        state: started
