---
- name: install apache
  hosts: debian
  roles:
    - role: '../roles/apache'

  tasks:
    - name: copy nextcloud.conf
      become: yes
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../apache/sites-available/nextcloud.conf"
        dest: /etc/apache2/sites-available
        owner: root
        group: root
        mode: '0644'

    - name: enable site
      become: yes
      ansible.builtin.shell: a2ensite nextcloud.conf

    - name: enable required modules
      become: yes
      block:
        - name: rewrite
          community.general.apache2_module:
            state: present
            name: rewrite
        - name: headers
          community.general.apache2_module:
            state: present
            name: headers
        - name: env
          community.general.apache2_module:
            state: present
            name: env
        - name: dir
          community.general.apache2_module:
            state: present
            name: dir
        - name: mime
          community.general.apache2_module:
            state: present
            name: mime

    - name: "workaround for debian bug #970862"
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/apache2/envvars
        line: 'export LD_PRELOAD="libgomp.so.1:${LD_PRELOAD}"'
