---
- name: Install papermc
  hosts: debian
  vars:
    user: "{{ ansible_user }}"
  tasks:
    - name: Download jar
      ansible.builtin.get_url:
        url: https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/186/downloads/paper-1.17.1-186.jar
        dest: ~/minecraft/paperclip.jar

    - name: Install systemd unit file
      become: yes
      block:
        - name: Copy start service
          ansible.builtin.template:
            src: '{{ playbook_dir }}/papermc.service.j2'
            dest: '/etc/systemd/system/papermc.service'
            mode: 0755
        - name: Copy start timer
          ansible.builtin.template:
            src: '{{ playbook_dir }}/papermc.timer.j2'
            dest: '/etc/systemd/system/papermc.timer'
            mode: 0755
        - name: Copy stop service
          ansible.builtin.template:
            src: '{{ playbook_dir }}/stop-papermc.service.j2'
            dest: '/etc/systemd/system/stop-papermc.service'
            mode: 0755
        - name: Copy stop timer
          ansible.builtin.template:
            src: '{{ playbook_dir }}/stop-papermc.timer.j2'
            dest: '/etc/systemd/system/stop-papermc.timer'
            mode: 0755
