- name: Install docker
  become: yes
  ansible.builtin.apt:
    name: docker-compose

- name: Add user to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start docker daemon
  become: yes
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
