- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - autoconf
      - build-essential
      - libopenjp2-7
      - libtiff5
      - tzdata
      - acl

- name: Add homeassistant user
  become: yes
  ansible.builtin.user:
    name: homeassistant
    system: yes
    create_home: yes

- name: Create virtual environment directory
  become: yes
  ansible.builtin.file:
    path: /srv/homeassistant
    state: directory
    owner: homeassistant
    group: homeassistant

- name: Create virtual environment
  become: yes
  become_user: homeassistant
  become_flags: '-H -s'
  ansible.builtin.pip:
    chdir: /srv/homeassistant
    virtualenv: /srv/homeassistant
    virtualenv_command: python3 -m venv
    name:
      - wheel
      - homeassistant

- name: Copy systemd unit file
  become: yes
  ansible.builtin.template:
    src: homeassistant.service.j2
    dest: '/etc/systemd/system/homeassistant.service'
    mode: 0644

- name: Start and enable systemd service
  become: yes
  ansible.builtin.service:
    name: homeassistant
    state: started
    enabled: yes
