- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - autoconf
      - build-essential
      - libopenjp2-7
      - libtiff5
      - tzdata
      - acl

- name: Add homeassistant user
  become: yes
  ansible.builtin.user:
    name: homeassistant
    system: yes
    create_home: yes

- name: Create virtual environment directory
  become: yes
  ansible.builtin.file:
    path: /srv/homeassistant
    state: directory
    owner: homeassistant
    group: homeassistant

- name: Create virtual environment
  become: yes
  become_user: homeassistant
  become_flags: '-H -s'
  ansible.builtin.pip:
    chdir: /srv/homeassistant
    virtualenv: /srv/homeassistant
    virtualenv_command: python3 -m venv
    name:
      - wheel
      - homeassistant

- name: Copy systemd unit file
  become: yes
  ansible.builtin.template:
    src: homeassistant.service.j2
    dest: '/etc/systemd/system/homeassistant.service'
    mode: 0644

- name: Start and enable systemd service
  become: yes
  ansible.builtin.service:
    name: homeassistant
    state: restarted
    enabled: yes

- name: Make homeassistant trust local proxies
  become: yes
  become_user: homeassistant
  ansible.builtin.blockinfile:
    path: /home/homeassistant/.homeassistant/configuration.yaml
    block: |
      http:
        use_x_forwarded_for: true
        trusted_proxies:
          - 127.0.0.1
          - ::1

- name: Restart homeassistant
  become: yes
  ansible.builtin.service:
    name: homeassistant
    state: restarted

- name: Enable required apache modules
  become: yes
  block:
    - name: proxy
      community.general.apache2_module:
        state: present
        name: proxy
    - name: proxy_http
      community.general.apache2_module:
        state: present
        name: proxy_http
    - name: proxy_ajp
      community.general.apache2_module:
        state: present
        name: proxy_ajp
    - name: rewrite
      community.general.apache2_module:
        state: present
        name: rewrite
    - name: deflate
      community.general.apache2_module:
        state: present
        name: deflate
    - name: headers
      community.general.apache2_module:
        state: present
        name: headers
    - name: proxy_balancer
      community.general.apache2_module:
        state: present
        name: proxy_balancer
    - name: proxy_connect
      community.general.apache2_module:
        state: present
        name: proxy_connect
    - name: proxy_html
      community.general.apache2_module:
        state: present
        name: proxy_html

- name: Configure apache proxy
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/apache2/sites-available/homeassistant-proxy.conf
    create: yes
    block: |
      <VirtualHost *:80>
        ServerName "homeassistant.{{ server_address }}"
        ServerAlias "*.homeassistant.{{ server_address }}" homeassistant
        ProxyPass "/" "http://localhost:8123/"
        ProxyPassReverse "/" "http://localhost:8123/"
        ProxyPreserveHost On
      </VirtualHost>

- name: Enable apache proxy conf
  become: yes
  ansible.builtin.command:
    cmd: a2ensite homeassistant-proxy

- name: Restart apache
  become: yes
  ansible.builtin.service:
    name: apache2
    state: restarted
